package ezcontent.qa.pages;

import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import ezcontent.qa.base.TestBase;
import ezcontent.qa.util.TestUtil;
import ezcontent.qa.util.Wait;

public class SmartArticlePage extends TestBase {
	@FindBy(id = "edit-title-0-value")
	WebElement titleField;

	@FindBy(id = "edit-field-company-name-0-value")
	WebElement chooseCompany;
	
	@FindBy(id = "edit-generate-summary")
	WebElement generateArticleContent;
	
	@FindBy(xpath = "//div[@id='cke_1_contents']//iframe[@class='cke_wysiwyg_frame cke_reset']")
	WebElement autoGeneratedIframe;
	
	@FindBy(xpath = "//body[@class='cke_editable cke_editable_themed cke_contents_ltr cke_show_borders']")
	WebElement iframeBody;
	
	@FindBy(id = "edit-field-company-logo-0-upload")
	WebElement uploadImage;
	@FindBy(xpath = "//input[@class='button--extrasmall remove-button button js-form-submit form-submit']")
	WebElement removeImage;
		
	@FindBy(xpath = "//div[@id='cke_2_contents']//iframe[@class='cke_wysiwyg_frame cke_reset']")
	WebElement articleBodyIframe;
	
	@FindBy(xpath = "//summary[contains(text(),'Generate Summary')]")
	WebElement generateSummaryTitle;
	@FindBy(id = "edit-field-smart-text-summary-0-summary-container-summary-area")
	WebElement summaryField;
	@FindBy(id = "edit-field-smart-text-summary-0-summary-container-generate-smart-summary")
	WebElement generateSummaryButton;
	
	@FindBy(id = "edit-submit")
	WebElement saveButton;
				
	public SmartArticlePage() {
		PageFactory.initElements(driver, this);
	}

	public void createSmartArticle(String title,String autoGeneratedcontent,String articlebody,String summarytext) {
		
		titleField.sendKeys(title);
//		chooseCompany.sendKeys("General Motors Co.");
//		chooseCompany.sendKeys(Keys.ENTER);
		TestUtil.viewportWebElement(chooseCompany);
		generateArticleContent.click();
		Wait.visibiltyOfElement(10, autoGeneratedIframe);
		TestUtil.switchFrameByWebElement(autoGeneratedIframe);	
		System.out.println("swith to frame window 1");
		iframeBody.sendKeys(autoGeneratedcontent);
		TestUtil.switchBackToWindow();	
		
		TestUtil.scroll(0, 300);
		uploadImage.sendKeys(imagepath1);		
		Wait.visibiltyOfElement(15, removeImage);
		
		TestUtil.switchFrameByWebElement(articleBodyIframe);
		System.out.println("swith to frame window 2");
		iframeBody.sendKeys(articlebody);
		TestUtil.switchBackToWindow();
		TestUtil.viewportWebElement(articleBodyIframe);
		generateSummaryTitle.click();
		summaryField.sendKeys(summarytext);
		saveButton.click();
		
	}
	
}
